version: 0.2

phases:
  install:
    commands:
      - echo "Install phase started"

  pre_build:
    commands:
      - echo "Fixing line endings"
      - sed -i 's/\r$//' s3-bucket.yml
      - echo "Validating CloudFormation template"
      - aws cloudformation validate-template --template-body file://s3-bucket.yml

  build:
    commands:
      - echo "Build phase started"
      - echo "Build successful"

artifacts:
  files:
    - s3-bucket.yml
