version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing cfn-lint"
      - pip install cfn-lint

  pre_build:
    commands:
      - echo "Validating CloudFormation template locally"
      - cfn-lint s3-bucket.yml

  build:
    commands:
      - echo "Build phase successful"

artifacts:
  files:
    - s3-bucket.yml
